### ISSUE TITLE
No pixel size denominator when calculating the derivatives

### ISSUE THREAD

**Issue by mfkasim1** [vc-bonn/Unsupervised_Deep_Learning_of_Incompressible_Fluid_Dynamics#1]
I notice that no pixel size is involved in the denominator when calculating the derivatives in your code, e.g. https://github.com/aschethor/Unsupervised_Deep_Learning_of_Incompressible_Fluid_Dynamics/blob/89bed1865cb83461de8682bd22614264f2d06b99/derivatives.py#L56-L58.
Could you please explain why this is the case?
What effect would it bring if you include the pixel size as the denominator?

**Comment by wandeln** [comment]
Hi @mfkasim1 ,
that's a good point. So far, we only considered grid cells of size 1, so no denominator was needed.
If you want to change the size of the grid cells, I would suggest 2 options:
1.) The "quick and dirty" way: you do dimensional scaling: if you divide the viscosity mu and dt by the size of the grid cells dx, you should obtain basically the same solutions as if you would simulate the fluid with viscosity mu and dt on a grid with cells of size dx.
2.) The slighly more elaborate but "proper" way: you introduce an additional parameter for dx in get_param.py and include this parameter in all derivatives inside derivatives.py.
I hope, I was able to answer your questions and if there are further questions or remarks, please let me know :)
Best regards,
Nils
