### ISSUE TITLE
Initial conditions

### ISSUE THREAD

**Issue by yhl48** [vc-bonn/Unsupervised_Deep_Learning_of_Incompressible_Fluid_Dynamics#4]
In Section 3.4 of the paper, it is said that

> For t = 0, we consider initial states p0 = 0 and a0 = 0, however, other initial conditions could be considered as well.

Could you please clarify why these initial conditions were chosen and how would other initial conditions affect the modelling?

**Comment by wandeln** [comment]
Hi!
These initial conditions were just chosen for simplicity.
Another option would be to compute initial conditions using e.g. a traditional fluid solver. We guess this would decrease the high initial losses during the "warm-up phase" of the simulation (see e.g. first 70 iterations in Figure 4).
However, this warm-up phase is very short (at 311 TPS less than 0.24 s) and causes no stability problems for the simulation of the neural network. So by starting with 0-initialized fields we can really learn the fluid dynamics "from scratch" and completely avoid expensive precomputations with traditional solvers for ground truth data or initial conditions.
I hope this helps. Let me know if there are further questions / remarks!
Best regards,
Nils
